"""Add use_whisper and whisper_model to analysis_tasks

Revision ID: febae0a64eed
Revises: 759dd1da1e5d
Create Date: 2026-03-29 22:52:24.715511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febae0a64eed'
down_revision: Union[str, Sequence[str], None] = '759dd1da1e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('use_whisper', sa.Integer(), nullable=True))
    op.add_column('analysis_tasks', sa.Column('whisper_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'whisper_model')
    op.drop_column('analysis_tasks', 'use_whisper')
    # ### end Alembic commands ###
